apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mainlb
  namespace: todo
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  ingressClassName: alb
  rules:
    - host: 
      http:
        paths:
          - path: /java
            pathType: Prefix
            backend:
              service:
                name: java-service
                port:
                  number: 8080
          - path: /rust
            pathType: Prefix
            backend:
              service:
                name: rust-service
                port:
                  number: 8000
          - path: /go-1
            pathType: Prefix
            backend:
              service:
                name: go-1-service
                port:
                  number: 9090
          - path: /go-2
            pathType: Prefix
            backend:
              service:
                name: go-2-service
                port:
                  number: 8086
          - path: /cors
            pathType: Prefix
            backend:
              service:
                name: cors-service
                port:
                  number: 9000                               
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
