# CICD using GitHub actions

name: CI-pipeline

on:
  push:
    branches:
      - exp1
   

jobs:

  build-and-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install SonarQube Scanner
      run: npm install -g sonarqube-scanner

    - name: Run SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=frontend-app \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
  push:
    runs-on: ubuntu-latest
    # Docker build and push 
    needs: build-and-scan
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{github.run_id}}

  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: https://github.com/shubham9511s/manifest-file.git
          ref: main

      - name: Update Deployment file
        env:
          GIT_REPO_NAME: "manifest-file"
          GIT_USER_NAME: "shubham9511s"
          REPO_IMAGE_NAME: "shubhamshinde2206/frontend"
        run: |
          git config user.email "shubham.ssc100@gmail.com"
          git config user.name "shubham9511s"
          imageTag=$(grep -oP '(?<=frontend:)[^ ]+' todo/main.yml)
          echo $imageTag
          sed -i "s|${REPO_IMAGE_NAME}:${imageTag}|${REPO_IMAGE_NAME}:${github.run_id}|" manifest/main.yml
          git add todo-k8s/ci.yml
          git commit -m "Update deployment Image to version ${github.run._id}"
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@v2
        with:
          github_token: ${{ secrets.GIT_TOKEN }}