# CICD using GitHub actions

name: CI-pipeline

on:
  push:
    branches:
      - exp1
   

jobs:

  build-and-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install SonarQube Scanner
      run: npm install -g sonarqube-scanner

    - name: Run SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=frontend-app \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
  push:
    runs-on: ubuntu-latest
    # Docker build and push 
    needs: build-and-scan
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{github.run_id}}

  update-helm-chart:
    runs-on: ubuntu-latest
    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}
        repository: shubham9511s/manifest-file
        path: todo-k8s

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' todo-k8s/frontend.yml

    - name: Commit and push changes
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        cd manifest-file
        git config --global user.email "shubham.ssc100@gmail.com"
        git config --global user.name "shubham9511s"
        git add todo-k8s/frontend.yaml
        git commit -m "Update tag in github to ${github.run.id}"
        git push https://${GIT_TOKEN}@github.com/shubham9511s/manifest-file.git HEAD:main      