# CICD using GitHub actions

name: CI-pipeline

on:
  push:
    branches:
      - exp1
   

jobs:

  build-and-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install SonarQube Scanner
      run: npm install -g sonarqube-scanner

    - name: Run SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=frontend-app \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
  push:
    runs-on: ubuntu-latest
    # Docker build and push 
    needs: build-and-scan
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{github.run_id}}

  update-newtag-in-github-repo:
    runs-on: ubuntu-latest
    needs: push
    steps:
    - name: Checkout the manifest repository
      uses: actions/checkout@v3
      with:
        repository: shubham9511s/manifest-file  # Replace with your git repo
        token: ${{ secrets.GIT_TOKEN }}

    - name: Update tag in repo
      run: |
        cd todo-k8s 
        if [ -f "frontend.yml" ]; then
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' frontend.yml
        else
          echo "frontend.yaml not found!"
          exit 1
        fi

    - name: Commit and push changes
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config --global user.email "shubham.ssc100@gmail.com"
        git config --global user.name "shubham9511s"
        git add frontend.yml
        git commit -m "Update tag in repo to ${github.run_id}"
        git push